-- nflverse schedules (release asset schedules/games.csv). Owner: nflverse.schedules.
-- Column names are the source's own, verbatim (REBUILD_DESIGN principle 4).
-- Scores and result are NULL until a game is played; that is what the
-- completeness gate reads (fdb/schedule.py). gametime is US Eastern.
CREATE TABLE core_schedule (
  game_id TEXT PRIMARY KEY,
  season INTEGER NOT NULL,
  game_type TEXT NOT NULL,
  week INTEGER NOT NULL,
  gameday TEXT NOT NULL,
  weekday TEXT,
  gametime TEXT,
  away_team TEXT NOT NULL,
  away_score INTEGER,
  home_team TEXT NOT NULL,
  home_score INTEGER,
  location TEXT,
  result INTEGER,
  total INTEGER,
  overtime INTEGER,
  old_game_id TEXT,
  gsis TEXT,
  nfl_detail_id TEXT,
  pfr TEXT,
  pff TEXT,
  espn TEXT,
  ftn TEXT,
  away_rest INTEGER,
  home_rest INTEGER,
  away_moneyline INTEGER,
  home_moneyline INTEGER,
  spread_line REAL,
  away_spread_odds INTEGER,
  home_spread_odds INTEGER,
  total_line REAL,
  under_odds INTEGER,
  over_odds INTEGER,
  div_game INTEGER,
  roof TEXT,
  surface TEXT,
  temp INTEGER,
  wind INTEGER,
  away_qb_id TEXT,
  home_qb_id TEXT,
  away_qb_name TEXT,
  home_qb_name TEXT,
  away_coach TEXT,
  home_coach TEXT,
  referee TEXT,
  stadium_id TEXT,
  stadium TEXT,
  -- framework columns: season_type derived from game_type (REG -> REG, WC/DIV/CON/SB -> POST)
  season_type TEXT NOT NULL CHECK (season_type IN ('REG','POST')),
  load_id INTEGER NOT NULL REFERENCES load_log(load_id)
);
CREATE INDEX ix_core_schedule_season_week ON core_schedule(season, season_type, week);
