-- nflverse players (release asset players/players.csv): nflverse's curated person table.
-- One row per gsis_id, every era. Owner: nflverse.players. Current-state feed.
-- NOTE: draft_pick here is the OVERALL pick (Jake Matthews 6, Brian Urlacher 9).
CREATE TABLE core_nflverse_players (
  gsis_id TEXT PRIMARY KEY,
  display_name TEXT,
  common_first_name TEXT,
  first_name TEXT,
  last_name TEXT,
  short_name TEXT,
  football_name TEXT,
  suffix TEXT,
  esb_id TEXT,
  nfl_id TEXT,
  pfr_id TEXT,
  pff_id TEXT,
  otc_id TEXT,
  espn_id TEXT,
  smart_id TEXT,
  birth_date TEXT,
  position_group TEXT,
  position TEXT,
  ngs_position_group TEXT,
  ngs_position TEXT,
  height INTEGER,
  weight INTEGER,
  headshot TEXT,
  college_name TEXT,
  college_conference TEXT,
  jersey_number INTEGER,
  rookie_season INTEGER,
  last_season INTEGER,
  latest_team TEXT,
  status TEXT,
  ngs_status TEXT,
  ngs_status_short_description TEXT,
  years_of_experience INTEGER,
  pff_position TEXT,
  pff_status TEXT,
  draft_year INTEGER,
  draft_round INTEGER,
  draft_pick INTEGER,
  draft_team TEXT,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id)
);

-- nflverse weekly rosters (release assets weekly_rosters/roster_weekly_<season>.csv), 2016-.
-- Owner: nflverse.rosters_weekly. Scope = season. Rosters are FORWARD-LOOKING (a week's roster
-- exists before its games), so there is no completeness gate on this table.
-- A few rows have no gsis_id (4 in 2026 at first load); they are kept and reported.
CREATE TABLE core_rosters_weekly (
  season INTEGER NOT NULL,
  team TEXT,
  position TEXT,
  depth_chart_position TEXT,
  jersey_number INTEGER,
  status TEXT,
  full_name TEXT,
  first_name TEXT,
  last_name TEXT,
  birth_date TEXT,
  height INTEGER,
  weight INTEGER,
  college TEXT,
  gsis_id TEXT,
  espn_id TEXT,
  sportradar_id TEXT,
  yahoo_id TEXT,
  rotowire_id TEXT,
  pff_id TEXT,
  pfr_id TEXT,
  fantasy_data_id TEXT,
  sleeper_id TEXT,
  years_exp INTEGER,
  headshot_url TEXT,
  ngs_position TEXT,
  week INTEGER NOT NULL,
  game_type TEXT,
  status_description_abbr TEXT,
  football_name TEXT,
  esb_id TEXT,
  gsis_it_id TEXT,
  smart_id TEXT,
  entry_year INTEGER,
  rookie_year INTEGER,
  draft_club TEXT,
  draft_number INTEGER,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id)
);

-- DynastyProcess db_playerids.csv (raw.githubusercontent.com/dynastyprocess/data). Owner: dynastyprocess.playerids.
-- Used ONLY as a source of mfl_id (and sleeper_id where nflverse has none). It contains
-- name-derived errors (one gsis_id on 'Kevin Smith' AND 'Fred Williams'), so every mapping
-- taken from it passes a negative name check in fdb/identity.py. 'NA' is its blank.
CREATE TABLE core_dp_playerids (
  mfl_id TEXT PRIMARY KEY,
  sportradar_id TEXT,
  fantasypros_id TEXT,
  gsis_id TEXT,
  pff_id TEXT,
  sleeper_id TEXT,
  nfl_id TEXT,
  espn_id TEXT,
  yahoo_id TEXT,
  fleaflicker_id TEXT,
  cbs_id TEXT,
  pfr_id TEXT,
  cfbref_id TEXT,
  rotowire_id TEXT,
  rotoworld_id TEXT,
  ktc_id TEXT,
  stats_id TEXT,
  stats_global_id TEXT,
  fantasy_data_id TEXT,
  swish_id TEXT,
  name TEXT,
  merge_name TEXT,
  position TEXT,
  team TEXT,
  birthdate TEXT,
  age REAL,
  draft_year INTEGER,
  draft_round INTEGER,
  draft_pick INTEGER,
  draft_ovr INTEGER,
  twitter_username TEXT,
  height INTEGER,
  weight INTEGER,
  college TEXT,
  db_season INTEGER,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id)
);

CREATE INDEX ix_core_rosters_weekly_season ON core_rosters_weekly(season, week);
CREATE INDEX ix_core_rosters_weekly_gsis ON core_rosters_weekly(gsis_id);
