-- nflverse stats_player_week_<season>.csv (nflreadr load_player_stats). Owner: nflverse.player_stats.
-- player_id IS a gsis_id. REG+POST. Weekly counts, source names verbatim.
CREATE TABLE core_player_stats (
  player_id TEXT,
  player_name TEXT,
  player_display_name TEXT,
  position TEXT,
  position_group TEXT,
  headshot_url TEXT,
  season INTEGER,
  week INTEGER,
  season_type TEXT,
  game_id TEXT,
  team TEXT,
  opponent_team TEXT,
  completions INTEGER,
  attempts INTEGER,
  passing_yards INTEGER,
  passing_tds INTEGER,
  passing_interceptions INTEGER,
  sacks_suffered INTEGER,
  sack_yards_lost INTEGER,
  sack_fumbles INTEGER,
  sack_fumbles_lost INTEGER,
  passing_air_yards INTEGER,
  passing_yards_after_catch INTEGER,
  passing_first_downs INTEGER,
  passing_epa REAL,
  passing_cpoe REAL,
  passing_2pt_conversions INTEGER,
  pacr REAL,
  passing_10 INTEGER,
  passing_16 INTEGER,
  passing_20 INTEGER,
  passing_40 INTEGER,
  carries INTEGER,
  rushing_yards INTEGER,
  rushing_tds INTEGER,
  rushing_fumbles INTEGER,
  rushing_fumbles_lost INTEGER,
  rushing_first_downs INTEGER,
  rushing_epa REAL,
  rushing_2pt_conversions INTEGER,
  rushing_10 INTEGER,
  rushing_12 INTEGER,
  rushing_20 INTEGER,
  rushing_40 INTEGER,
  receptions INTEGER,
  targets INTEGER,
  receiving_yards INTEGER,
  receiving_tds INTEGER,
  receiving_fumbles INTEGER,
  receiving_fumbles_lost INTEGER,
  receiving_air_yards INTEGER,
  receiving_yards_after_catch INTEGER,
  receiving_first_downs INTEGER,
  receiving_epa REAL,
  receiving_2pt_conversions INTEGER,
  receiving_10 INTEGER,
  receiving_16 INTEGER,
  receiving_20 INTEGER,
  receiving_40 INTEGER,
  racr REAL,
  target_share REAL,
  air_yards_share REAL,
  wopr REAL,
  special_teams_tds INTEGER,
  def_tackles_solo INTEGER,
  def_tackles_with_assist INTEGER,
  def_tackle_assists INTEGER,
  def_tackles_for_loss INTEGER,
  def_tackles_for_loss_yards INTEGER,
  def_fumbles_forced INTEGER,
  def_sacks REAL,
  def_sack_yards REAL,
  def_qb_hits INTEGER,
  def_interceptions INTEGER,
  def_interception_yards INTEGER,
  def_pass_defended INTEGER,
  def_tds INTEGER,
  def_fumbles INTEGER,
  def_safeties INTEGER,
  def_punt_blocks INTEGER,
  def_pat_blocks INTEGER,
  def_fg_blocks INTEGER,
  def_2pt_atts INTEGER,
  def_2pt_made INTEGER,
  misc_yards INTEGER,
  fumble_recovery_own INTEGER,
  fumble_recovery_yards_own INTEGER,
  fumble_recovery_opp INTEGER,
  fumble_recovery_yards_opp INTEGER,
  fumble_recovery_tds INTEGER,
  penalties INTEGER,
  penalty_yards INTEGER,
  fumbles_forced_by_opp INTEGER,
  fumbles_not_forced INTEGER,
  fumbles_out_of_bounds INTEGER,
  fumbles_total INTEGER,
  fumbles_lost_total INTEGER,
  punt_returns INTEGER,
  punt_return_yards INTEGER,
  kickoff_returns INTEGER,
  kickoff_return_yards INTEGER,
  fg_made INTEGER,
  fg_att INTEGER,
  fg_missed INTEGER,
  fg_blocked INTEGER,
  fg_long INTEGER,
  fg_pct REAL,
  fg_made_0_19 INTEGER,
  fg_made_20_29 INTEGER,
  fg_made_30_39 INTEGER,
  fg_made_40_49 INTEGER,
  fg_made_50_59 INTEGER,
  fg_made_60_ INTEGER,
  fg_missed_0_19 INTEGER,
  fg_missed_20_29 INTEGER,
  fg_missed_30_39 INTEGER,
  fg_missed_40_49 INTEGER,
  fg_missed_50_59 INTEGER,
  fg_missed_60_ INTEGER,
  fg_made_list TEXT,
  fg_missed_list TEXT,
  fg_blocked_list TEXT,
  fg_made_distance INTEGER,
  fg_missed_distance INTEGER,
  fg_blocked_distance INTEGER,
  pat_made INTEGER,
  pat_att INTEGER,
  pat_missed INTEGER,
  pat_blocked INTEGER,
  pat_pct REAL,
  gwfg_made INTEGER,
  gwfg_att INTEGER,
  gwfg_missed INTEGER,
  gwfg_blocked INTEGER,
  gwfg_distance INTEGER,
  pt_att INTEGER,
  pt_blocked INTEGER,
  pt_long INTEGER,
  pt_yards INTEGER,
  pt_inside_20 INTEGER,
  pt_out_of_bounds INTEGER,
  pt_downed INTEGER,
  pt_touchback INTEGER,
  pt_fair_caught INTEGER,
  pt_returned INTEGER,
  pt_return_yards INTEGER,
  pt_return_tds INTEGER,
  pt_net_yards INTEGER,
  fantasy_points REAL,
  fantasy_points_ppr REAL,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (game_id, player_id)
);

-- nflverse snap_counts_<season>.csv (PFR). Owner: nflverse.snap_counts. Player key is pfr_player_id
-- (-> gsis via player_ids source 'pfr'). season_type derived from game_type.
CREATE TABLE core_snap_counts (
  game_id TEXT,
  pfr_game_id TEXT,
  season INTEGER,
  game_type TEXT,
  week INTEGER,
  player TEXT,
  pfr_player_id TEXT,
  position TEXT,
  team TEXT,
  opponent TEXT,
  offense_snaps INTEGER,
  offense_pct REAL,
  defense_snaps INTEGER,
  defense_pct REAL,
  st_snaps INTEGER,
  st_pct REAL,
  season_type TEXT NOT NULL,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (game_id, pfr_player_id)
);

-- nflverse play_by_play_<season>.csv.gz, 117 of ~372 columns (list = contracts/nflverse.pbp.fields).
-- Owner: nflverse.pbp. Player id columns are gsis_ids.
CREATE TABLE core_pbp (
  play_id INTEGER,
  game_id TEXT,
  home_team TEXT,
  away_team TEXT,
  season_type TEXT,
  week INTEGER,
  posteam TEXT,
  posteam_type TEXT,
  defteam TEXT,
  yardline_100 INTEGER,
  game_date TEXT,
  half_seconds_remaining INTEGER,
  game_seconds_remaining INTEGER,
  drive INTEGER,
  qtr INTEGER,
  down INTEGER,
  goal_to_go INTEGER,
  ydstogo INTEGER,
  play_type TEXT,
  yards_gained INTEGER,
  shotgun INTEGER,
  no_huddle INTEGER,
  qb_dropback INTEGER,
  qb_kneel INTEGER,
  qb_spike INTEGER,
  qb_scramble INTEGER,
  pass_length TEXT,
  pass_location TEXT,
  air_yards INTEGER,
  yards_after_catch INTEGER,
  run_location TEXT,
  run_gap TEXT,
  field_goal_result TEXT,
  kick_distance INTEGER,
  extra_point_result TEXT,
  two_point_conv_result TEXT,
  td_player_id TEXT,
  posteam_score INTEGER,
  defteam_score INTEGER,
  score_differential INTEGER,
  epa REAL,
  air_epa REAL,
  yac_epa REAL,
  comp_air_epa REAL,
  comp_yac_epa REAL,
  wp REAL,
  wpa REAL,
  vegas_wp REAL,
  first_down_rush INTEGER,
  first_down_pass INTEGER,
  first_down_penalty INTEGER,
  third_down_converted INTEGER,
  third_down_failed INTEGER,
  fourth_down_converted INTEGER,
  fourth_down_failed INTEGER,
  incomplete_pass INTEGER,
  interception INTEGER,
  penalty INTEGER,
  fumble_lost INTEGER,
  qb_hit INTEGER,
  rush_attempt INTEGER,
  pass_attempt INTEGER,
  sack INTEGER,
  touchdown INTEGER,
  pass_touchdown INTEGER,
  rush_touchdown INTEGER,
  return_touchdown INTEGER,
  two_point_attempt INTEGER,
  fumble INTEGER,
  complete_pass INTEGER,
  passer_player_id TEXT,
  receiver_player_id TEXT,
  rusher_player_id TEXT,
  interception_player_id TEXT,
  tackle_for_loss_1_player_id TEXT,
  tackle_for_loss_2_player_id TEXT,
  qb_hit_1_player_id TEXT,
  qb_hit_2_player_id TEXT,
  forced_fumble_player_1_player_id TEXT,
  forced_fumble_player_2_player_id TEXT,
  solo_tackle_1_player_id TEXT,
  solo_tackle_2_player_id TEXT,
  assist_tackle_1_player_id TEXT,
  assist_tackle_2_player_id TEXT,
  assist_tackle_3_player_id TEXT,
  assist_tackle_4_player_id TEXT,
  tackle_with_assist_1_player_id TEXT,
  tackle_with_assist_2_player_id TEXT,
  pass_defense_1_player_id TEXT,
  pass_defense_2_player_id TEXT,
  fumbled_1_player_id TEXT,
  fumble_recovery_1_team TEXT,
  fumble_recovery_1_player_id TEXT,
  sack_player_id TEXT,
  half_sack_1_player_id TEXT,
  half_sack_2_player_id TEXT,
  penalty_team TEXT,
  penalty_yards INTEGER,
  penalty_type TEXT,
  season INTEGER,
  cp REAL,
  cpoe REAL,
  series_success INTEGER,
  special_teams_play INTEGER,
  roof TEXT,
  surface TEXT,
  aborted_play INTEGER,
  success INTEGER,
  pass INTEGER,
  rush INTEGER,
  first_down INTEGER,
  special INTEGER,
  play INTEGER,
  fantasy_player_id TEXT,
  xyac_epa REAL,
  xpass REAL,
  pass_oe REAL,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (game_id, play_id)
);

-- nflverse pbp_participation_<season>.csv, 2016-2025 ONLY (nflverse stops at 2025; 2026 comes from FTN
-- in Phase 5). Owner: nflverse.participation. offense_players/defense_players are ';'-separated
-- gsis_ids. Name/jersey lists deliberately NOT stored. season/season_type/week derived from the
-- schedule via nflverse_game_id.
CREATE TABLE core_participation (
  nflverse_game_id TEXT,
  old_game_id TEXT,
  play_id INTEGER,
  possession_team TEXT,
  offense_formation TEXT,
  offense_personnel TEXT,
  defenders_in_box INTEGER,
  defense_personnel TEXT,
  number_of_pass_rushers INTEGER,
  players_on_play TEXT,
  offense_players TEXT,
  defense_players TEXT,
  n_offense INTEGER,
  n_defense INTEGER,
  ngs_air_yards REAL,
  time_to_throw REAL,
  was_pressure TEXT,
  route TEXT,
  defense_man_zone_type TEXT,
  defense_coverage_type TEXT,
  offense_positions TEXT,
  defense_positions TEXT,
  season INTEGER NOT NULL,
  season_type TEXT NOT NULL,
  week INTEGER NOT NULL,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (nflverse_game_id, play_id)
);

-- nflverse NGS passing (ngs_passing.csv.gz, all seasons). Owner: nflverse.ngs_passing.
-- week 0 = season total: NOT loaded. NGS numbers the Super Bowl one week later than the schedule
-- (skips Pro Bowl week): `week` is NGS's value verbatim, `schedule_week` is the schedule's.
CREATE TABLE core_ngs_passing (
  season INTEGER,
  season_type TEXT,
  week INTEGER,
  player_display_name TEXT,
  player_position TEXT,
  team_abbr TEXT,
  avg_time_to_throw REAL,
  avg_completed_air_yards REAL,
  avg_intended_air_yards REAL,
  avg_air_yards_differential REAL,
  aggressiveness REAL,
  max_completed_air_distance REAL,
  avg_air_yards_to_sticks REAL,
  attempts INTEGER,
  pass_yards INTEGER,
  pass_touchdowns INTEGER,
  interceptions INTEGER,
  passer_rating REAL,
  completions INTEGER,
  completion_percentage REAL,
  expected_completion_percentage REAL,
  completion_percentage_above_expectation REAL,
  avg_air_distance REAL,
  max_air_distance REAL,
  player_gsis_id TEXT,
  player_first_name TEXT,
  player_last_name TEXT,
  player_jersey_number INTEGER,
  player_short_name TEXT,
  schedule_week INTEGER NOT NULL,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (season, season_type, week, player_gsis_id)
);

-- nflverse NGS receiving. Same week rules as core_ngs_passing.
CREATE TABLE core_ngs_receiving (
  season INTEGER,
  season_type TEXT,
  week INTEGER,
  player_display_name TEXT,
  player_position TEXT,
  team_abbr TEXT,
  avg_cushion REAL,
  avg_separation REAL,
  avg_intended_air_yards REAL,
  percent_share_of_intended_air_yards REAL,
  receptions INTEGER,
  targets INTEGER,
  catch_percentage REAL,
  yards INTEGER,
  rec_touchdowns INTEGER,
  avg_yac REAL,
  avg_expected_yac REAL,
  avg_yac_above_expectation REAL,
  player_gsis_id TEXT,
  player_first_name TEXT,
  player_last_name TEXT,
  player_jersey_number INTEGER,
  player_short_name TEXT,
  schedule_week INTEGER NOT NULL,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (season, season_type, week, player_gsis_id)
);

-- nflverse NGS rushing. Same week rules as core_ngs_passing.
CREATE TABLE core_ngs_rushing (
  season INTEGER,
  season_type TEXT,
  week INTEGER,
  player_display_name TEXT,
  player_position TEXT,
  team_abbr TEXT,
  efficiency REAL,
  percent_attempts_gte_eight_defenders REAL,
  avg_time_to_los REAL,
  rush_attempts INTEGER,
  rush_yards INTEGER,
  avg_rush_yards REAL,
  rush_touchdowns INTEGER,
  player_gsis_id TEXT,
  player_first_name TEXT,
  player_last_name TEXT,
  player_jersey_number INTEGER,
  player_short_name TEXT,
  expected_rush_yards REAL,
  rush_yards_over_expected REAL,
  rush_yards_over_expected_per_att REAL,
  rush_pct_over_expected REAL,
  schedule_week INTEGER NOT NULL,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (season, season_type, week, player_gsis_id)
);

-- ffverse ffopportunity ep_weekly_<season>.csv (nflreadr load_ff_opportunity). Owner: ffverse.ff_opportunity.
-- player_id is a gsis_id. season_type derived from the schedule via game_id.
CREATE TABLE core_ff_opportunity (
  season INTEGER,
  posteam TEXT,
  week INTEGER,
  game_id TEXT,
  player_id TEXT,
  full_name TEXT,
  position TEXT,
  pass_attempt INTEGER,
  rec_attempt INTEGER,
  rush_attempt INTEGER,
  pass_air_yards INTEGER,
  rec_air_yards INTEGER,
  pass_completions INTEGER,
  receptions INTEGER,
  pass_completions_exp REAL,
  receptions_exp REAL,
  pass_yards_gained INTEGER,
  rec_yards_gained INTEGER,
  rush_yards_gained INTEGER,
  pass_yards_gained_exp REAL,
  rec_yards_gained_exp REAL,
  rush_yards_gained_exp REAL,
  pass_touchdown INTEGER,
  rec_touchdown INTEGER,
  rush_touchdown INTEGER,
  pass_touchdown_exp REAL,
  rec_touchdown_exp REAL,
  rush_touchdown_exp REAL,
  pass_two_point_conv INTEGER,
  rec_two_point_conv INTEGER,
  rush_two_point_conv INTEGER,
  pass_two_point_conv_exp REAL,
  rec_two_point_conv_exp REAL,
  rush_two_point_conv_exp REAL,
  pass_first_down INTEGER,
  rec_first_down INTEGER,
  rush_first_down INTEGER,
  pass_first_down_exp REAL,
  rec_first_down_exp REAL,
  rush_first_down_exp REAL,
  pass_interception INTEGER,
  rec_interception INTEGER,
  pass_interception_exp REAL,
  rec_interception_exp REAL,
  rec_fumble_lost INTEGER,
  rush_fumble_lost INTEGER,
  pass_fantasy_points_exp REAL,
  rec_fantasy_points_exp REAL,
  rush_fantasy_points_exp REAL,
  pass_fantasy_points REAL,
  rec_fantasy_points REAL,
  rush_fantasy_points REAL,
  total_yards_gained INTEGER,
  total_yards_gained_exp REAL,
  total_touchdown INTEGER,
  total_touchdown_exp REAL,
  total_first_down INTEGER,
  total_first_down_exp REAL,
  total_fantasy_points REAL,
  total_fantasy_points_exp REAL,
  pass_completions_diff REAL,
  receptions_diff REAL,
  pass_yards_gained_diff REAL,
  rec_yards_gained_diff REAL,
  rush_yards_gained_diff REAL,
  pass_touchdown_diff REAL,
  rec_touchdown_diff REAL,
  rush_touchdown_diff REAL,
  pass_two_point_conv_diff REAL,
  rec_two_point_conv_diff REAL,
  rush_two_point_conv_diff REAL,
  pass_first_down_diff REAL,
  rec_first_down_diff REAL,
  rush_first_down_diff REAL,
  pass_interception_diff REAL,
  rec_interception_diff REAL,
  pass_fantasy_points_diff REAL,
  rec_fantasy_points_diff REAL,
  rush_fantasy_points_diff REAL,
  total_yards_gained_diff REAL,
  total_touchdown_diff REAL,
  total_first_down_diff REAL,
  total_fantasy_points_diff REAL,
  pass_attempt_team INTEGER,
  rec_attempt_team INTEGER,
  rush_attempt_team INTEGER,
  pass_air_yards_team INTEGER,
  rec_air_yards_team INTEGER,
  pass_completions_team INTEGER,
  receptions_team INTEGER,
  pass_completions_exp_team REAL,
  receptions_exp_team REAL,
  pass_yards_gained_team INTEGER,
  rec_yards_gained_team INTEGER,
  rush_yards_gained_team INTEGER,
  pass_yards_gained_exp_team REAL,
  rec_yards_gained_exp_team REAL,
  rush_yards_gained_exp_team REAL,
  pass_touchdown_team INTEGER,
  rec_touchdown_team INTEGER,
  rush_touchdown_team INTEGER,
  pass_touchdown_exp_team REAL,
  rec_touchdown_exp_team REAL,
  rush_touchdown_exp_team REAL,
  pass_two_point_conv_team INTEGER,
  rec_two_point_conv_team INTEGER,
  rush_two_point_conv_team INTEGER,
  pass_two_point_conv_exp_team REAL,
  rec_two_point_conv_exp_team REAL,
  rush_two_point_conv_exp_team REAL,
  pass_first_down_team INTEGER,
  rec_first_down_team INTEGER,
  rush_first_down_team INTEGER,
  pass_first_down_exp_team REAL,
  rec_first_down_exp_team REAL,
  rush_first_down_exp_team REAL,
  pass_interception_team INTEGER,
  rec_interception_team INTEGER,
  pass_interception_exp_team REAL,
  rec_interception_exp_team REAL,
  rec_fumble_lost_team INTEGER,
  rush_fumble_lost_team INTEGER,
  pass_fantasy_points_exp_team REAL,
  rec_fantasy_points_exp_team REAL,
  rush_fantasy_points_exp_team REAL,
  pass_fantasy_points_team REAL,
  rec_fantasy_points_team REAL,
  rush_fantasy_points_team REAL,
  pass_completions_diff_team REAL,
  receptions_diff_team REAL,
  pass_yards_gained_diff_team REAL,
  rec_yards_gained_diff_team REAL,
  rush_yards_gained_diff_team REAL,
  pass_touchdown_diff_team REAL,
  rec_touchdown_diff_team REAL,
  rush_touchdown_diff_team REAL,
  pass_two_point_conv_diff_team REAL,
  rec_two_point_conv_diff_team REAL,
  rush_two_point_conv_diff_team REAL,
  pass_first_down_diff_team REAL,
  rec_first_down_diff_team REAL,
  rush_first_down_diff_team REAL,
  pass_interception_diff_team REAL,
  rec_interception_diff_team REAL,
  pass_fantasy_points_diff_team REAL,
  rec_fantasy_points_diff_team REAL,
  rush_fantasy_points_diff_team REAL,
  total_yards_gained_team INTEGER,
  total_yards_gained_exp_team REAL,
  total_yards_gained_diff_team REAL,
  total_touchdown_team INTEGER,
  total_touchdown_exp_team REAL,
  total_touchdown_diff_team REAL,
  total_first_down_team INTEGER,
  total_first_down_exp_team REAL,
  total_first_down_diff_team REAL,
  total_fantasy_points_team REAL,
  total_fantasy_points_exp_team REAL,
  total_fantasy_points_diff_team REAL,
  season_type TEXT NOT NULL,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (game_id, player_id)
);
CREATE INDEX ix_player_stats_scope ON core_player_stats(season, season_type, week);
CREATE INDEX ix_player_stats_player ON core_player_stats(player_id);
CREATE INDEX ix_snap_counts_scope ON core_snap_counts(season, season_type, week);
CREATE INDEX ix_pbp_scope ON core_pbp(season, season_type, week);
CREATE INDEX ix_participation_scope ON core_participation(season, season_type, week);
CREATE INDEX ix_ngs_passing_scope ON core_ngs_passing(season, season_type, schedule_week);
CREATE INDEX ix_ngs_receiving_scope ON core_ngs_receiving(season, season_type, schedule_week);
CREATE INDEX ix_ngs_rushing_scope ON core_ngs_rushing(season, season_type, schedule_week);
CREATE INDEX ix_ff_opportunity_scope ON core_ff_opportunity(season, season_type, week);
