-- PFF Developer API facets (REBUILD_DESIGN §4, Phase 4). Owner per table: registry/sources.toml.
-- Columns = PFF wire names verbatim (types from live 2016 + 2025 responses; the column
-- sets were identical in both). Framework columns: season, season_type, week (the
-- SCHEDULE's week) and pff_week (the week PFF was asked for: REG 1-18, POST 28/29/30/32).
-- PFF rows carry no week; the request defines it. PRE is never requested (no PFF week
-- number reaches it), which is how preseason stays out.

CREATE TABLE core_pff_defense_week (
  season INTEGER NOT NULL,
  season_type TEXT NOT NULL CHECK (season_type IN ('REG', 'POST')),
  week INTEGER NOT NULL,
  pff_week INTEGER NOT NULL,
  player_id INTEGER NOT NULL,
  player TEXT,
  position TEXT,
  team_name TEXT NOT NULL,
  team TEXT,
  franchise_id INTEGER NOT NULL,
  jersey_number TEXT,
  player_game_count INTEGER,
  draft_season INTEGER,
  eligible_season INTEGER,
  assists INTEGER,
  batted_passes INTEGER,
  catch_rate REAL,
  declined_penalties INTEGER,
  forced_fumbles INTEGER,
  fumble_recoveries INTEGER,
  fumble_recovery_touchdowns INTEGER,
  grades_coverage_defense REAL,
  grades_defense REAL,
  grades_defense_penalty REAL,
  grades_pass_rush_defense REAL,
  grades_run_defense REAL,
  grades_tackle REAL,
  hits INTEGER,
  hurries INTEGER,
  interception_touchdowns INTEGER,
  interceptions INTEGER,
  longest INTEGER,
  missed_tackle_rate REAL,
  missed_tackles INTEGER,
  pass_break_ups INTEGER,
  penalties INTEGER,
  qb_rating_against REAL,
  receptions INTEGER,
  sacks INTEGER,
  safeties INTEGER,
  snap_counts_box INTEGER,
  snap_counts_corner INTEGER,
  snap_counts_coverage INTEGER,
  snap_counts_defense INTEGER,
  snap_counts_dl INTEGER,
  snap_counts_dl_a_gap INTEGER,
  snap_counts_dl_b_gap INTEGER,
  snap_counts_dl_outside_t INTEGER,
  snap_counts_dl_over_t INTEGER,
  snap_counts_fs INTEGER,
  snap_counts_offball INTEGER,
  snap_counts_pass_rush INTEGER,
  snap_counts_run_defense INTEGER,
  snap_counts_slot INTEGER,
  stops INTEGER,
  tackles INTEGER,
  tackles_for_loss INTEGER,
  targets INTEGER,
  total_pressures INTEGER,
  touchdowns INTEGER,
  yards INTEGER,
  yards_after_catch INTEGER,
  yards_per_reception REAL,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (season, season_type, week, player_id)
);
CREATE INDEX ix_core_pff_defense_week_player ON core_pff_defense_week(player_id);

CREATE TABLE core_pff_fg_week (
  season INTEGER NOT NULL,
  season_type TEXT NOT NULL CHECK (season_type IN ('REG', 'POST')),
  week INTEGER NOT NULL,
  pff_week INTEGER NOT NULL,
  player_id INTEGER NOT NULL,
  player TEXT,
  position TEXT,
  team_name TEXT NOT NULL,
  team TEXT,
  franchise_id INTEGER NOT NULL,
  jersey_number TEXT,
  player_game_count INTEGER,
  draft_season INTEGER,
  eligible_season INTEGER,
  declined_penalties INTEGER,
  fifty_attempts INTEGER,
  fifty_made INTEGER,
  fifty_percent REAL,
  forty_attempts INTEGER,
  forty_made INTEGER,
  forty_percent REAL,
  grades_fgep_kicker REAL,
  one_attempts INTEGER,
  one_made INTEGER,
  one_percent REAL,
  pat_attempts INTEGER,
  pat_made INTEGER,
  pat_percent REAL,
  penalties INTEGER,
  thirty_attempts INTEGER,
  thirty_made INTEGER,
  thirty_percent REAL,
  total_attempts INTEGER,
  total_made INTEGER,
  total_percent REAL,
  twenty_attempts INTEGER,
  twenty_made INTEGER,
  twenty_percent REAL,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (season, season_type, week, player_id)
);
CREATE INDEX ix_core_pff_fg_week_player ON core_pff_fg_week(player_id);

CREATE TABLE core_pff_passing_week (
  season INTEGER NOT NULL,
  season_type TEXT NOT NULL CHECK (season_type IN ('REG', 'POST')),
  week INTEGER NOT NULL,
  pff_week INTEGER NOT NULL,
  player_id INTEGER NOT NULL,
  player TEXT,
  position TEXT,
  team_name TEXT NOT NULL,
  team TEXT,
  franchise_id INTEGER NOT NULL,
  jersey_number TEXT,
  player_game_count INTEGER,
  draft_season INTEGER,
  eligible_season INTEGER,
  accuracy_percent REAL,
  aimed_passes INTEGER,
  attempts INTEGER,
  avg_depth_of_target REAL,
  avg_time_to_throw REAL,
  bats INTEGER,
  big_time_throws INTEGER,
  btt_rate REAL,
  completion_percent REAL,
  completions INTEGER,
  declined_penalties INTEGER,
  def_gen_pressures INTEGER,
  drop_rate REAL,
  dropbacks INTEGER,
  drops INTEGER,
  epa REAL,
  first_downs INTEGER,
  grades_hands_fumble REAL,
  grades_offense REAL,
  grades_pass REAL,
  grades_run REAL,
  hit_as_threw INTEGER,
  interceptions INTEGER,
  passing_snaps INTEGER,
  penalties INTEGER,
  positive_epa_percent REAL,
  pressure_to_sack_rate REAL,
  qb_rating REAL,
  sack_percent REAL,
  sacks INTEGER,
  scrambles INTEGER,
  spikes INTEGER,
  thrown_aways INTEGER,
  touchdowns INTEGER,
  turnover_worthy_plays INTEGER,
  twp_rate REAL,
  yards INTEGER,
  ypa REAL,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (season, season_type, week, player_id)
);
CREATE INDEX ix_core_pff_passing_week_player ON core_pff_passing_week(player_id);

CREATE TABLE core_pff_rushing_week (
  season INTEGER NOT NULL,
  season_type TEXT NOT NULL CHECK (season_type IN ('REG', 'POST')),
  week INTEGER NOT NULL,
  pff_week INTEGER NOT NULL,
  player_id INTEGER NOT NULL,
  player TEXT,
  position TEXT,
  team_name TEXT NOT NULL,
  team TEXT,
  franchise_id INTEGER NOT NULL,
  jersey_number TEXT,
  player_game_count INTEGER,
  draft_season INTEGER,
  eligible_season INTEGER,
  attempts INTEGER,
  avoided_tackles INTEGER,
  breakaway_attempts INTEGER,
  breakaway_percent REAL,
  breakaway_yards INTEGER,
  declined_penalties INTEGER,
  designed_yards INTEGER,
  drops INTEGER,
  elu_recv_mtf INTEGER,
  elu_rush_mtf INTEGER,
  elu_yco INTEGER,
  elusive_rating REAL,
  explosive INTEGER,
  first_downs INTEGER,
  fumbles INTEGER,
  gap_attempts INTEGER,
  grades_hands_fumble REAL,
  grades_offense REAL,
  grades_offense_penalty REAL,
  grades_pass REAL,
  grades_pass_block REAL,
  grades_pass_route REAL,
  grades_run REAL,
  grades_run_block REAL,
  longest INTEGER,
  penalties INTEGER,
  rec_yards INTEGER,
  receptions INTEGER,
  routes INTEGER,
  run_plays INTEGER,
  scramble_yards INTEGER,
  scrambles INTEGER,
  targets INTEGER,
  total_touches INTEGER,
  touchdowns INTEGER,
  yards INTEGER,
  yards_after_contact INTEGER,
  yco_attempt REAL,
  ypa REAL,
  yprr REAL,
  zone_attempts INTEGER,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (season, season_type, week, player_id)
);
CREATE INDEX ix_core_pff_rushing_week_player ON core_pff_rushing_week(player_id);

CREATE TABLE core_pff_receiving_week (
  season INTEGER NOT NULL,
  season_type TEXT NOT NULL CHECK (season_type IN ('REG', 'POST')),
  week INTEGER NOT NULL,
  pff_week INTEGER NOT NULL,
  player_id INTEGER NOT NULL,
  player TEXT,
  position TEXT,
  team_name TEXT NOT NULL,
  team TEXT,
  franchise_id INTEGER NOT NULL,
  jersey_number TEXT,
  player_game_count INTEGER,
  draft_season INTEGER,
  eligible_season INTEGER,
  avg_depth_of_target REAL,
  avoided_tackles INTEGER,
  caught_percent REAL,
  contested_catch_rate REAL,
  contested_receptions INTEGER,
  contested_targets INTEGER,
  declined_penalties INTEGER,
  drop_rate REAL,
  drops INTEGER,
  epa REAL,
  first_downs INTEGER,
  fumbles INTEGER,
  grades_hands_drop REAL,
  grades_hands_fumble REAL,
  grades_offense REAL,
  grades_pass_block REAL,
  grades_pass_route REAL,
  inline_rate REAL,
  inline_snaps INTEGER,
  interceptions INTEGER,
  longest INTEGER,
  pass_block_rate REAL,
  pass_blocks INTEGER,
  pass_plays INTEGER,
  penalties INTEGER,
  positive_epa_percent REAL,
  receptions INTEGER,
  route_rate REAL,
  routes INTEGER,
  slot_rate REAL,
  slot_snaps INTEGER,
  targeted_qb_rating REAL,
  targets INTEGER,
  touchdowns INTEGER,
  wide_rate REAL,
  wide_snaps INTEGER,
  yards INTEGER,
  yards_after_catch INTEGER,
  yards_after_catch_per_reception REAL,
  yards_per_reception REAL,
  yprr REAL,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (season, season_type, week, player_id)
);
CREATE INDEX ix_core_pff_receiving_week_player ON core_pff_receiving_week(player_id);

CREATE TABLE core_pff_blocking_week (
  season INTEGER NOT NULL,
  season_type TEXT NOT NULL CHECK (season_type IN ('REG', 'POST')),
  week INTEGER NOT NULL,
  pff_week INTEGER NOT NULL,
  player_id INTEGER NOT NULL,
  player TEXT,
  position TEXT,
  team_name TEXT NOT NULL,
  team TEXT,
  franchise_id INTEGER NOT NULL,
  jersey_number TEXT,
  player_game_count INTEGER,
  draft_season INTEGER,
  eligible_season INTEGER,
  block_percent REAL,
  declined_penalties INTEGER,
  grades_offense REAL,
  grades_pass_block REAL,
  grades_run_block REAL,
  hits_allowed INTEGER,
  hurries_allowed INTEGER,
  non_spike_pass_block INTEGER,
  non_spike_pass_block_percentage REAL,
  pass_block_percent REAL,
  pbe REAL,
  penalties INTEGER,
  pressures_allowed INTEGER,
  sacks_allowed INTEGER,
  snap_counts_block INTEGER,
  snap_counts_ce INTEGER,
  snap_counts_lg INTEGER,
  snap_counts_lt INTEGER,
  snap_counts_offense INTEGER,
  snap_counts_pass_block INTEGER,
  snap_counts_pass_play INTEGER,
  snap_counts_rg INTEGER,
  snap_counts_rt INTEGER,
  snap_counts_run_block INTEGER,
  snap_counts_te INTEGER,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (season, season_type, week, player_id)
);
CREATE INDEX ix_core_pff_blocking_week_player ON core_pff_blocking_week(player_id);

CREATE TABLE core_pff_coverage_scheme_week (
  season INTEGER NOT NULL,
  season_type TEXT NOT NULL CHECK (season_type IN ('REG', 'POST')),
  week INTEGER NOT NULL,
  pff_week INTEGER NOT NULL,
  player_id INTEGER NOT NULL,
  player TEXT,
  position TEXT,
  team_name TEXT NOT NULL,
  team TEXT,
  franchise_id INTEGER NOT NULL,
  jersey_number TEXT,
  player_game_count INTEGER,
  draft_season INTEGER,
  eligible_season INTEGER,
  base_snap_counts_coverage INTEGER,
  declined_penalties INTEGER,
  man_assists INTEGER,
  man_avg_depth_of_target REAL,
  man_catch_rate REAL,
  man_coverage_percent REAL,
  man_coverage_snaps_per_reception REAL,
  man_coverage_snaps_per_target REAL,
  man_dropped_ints INTEGER,
  man_forced_incompletes INTEGER,
  man_forced_incompletion_rate REAL,
  man_grades_coverage_defense REAL,
  man_interceptions INTEGER,
  man_longest INTEGER,
  man_missed_tackle_rate REAL,
  man_missed_tackles INTEGER,
  man_pass_break_ups INTEGER,
  man_qb_rating_against REAL,
  man_receptions INTEGER,
  man_snap_counts_coverage INTEGER,
  man_snap_counts_coverage_percent REAL,
  man_snap_counts_pass_play INTEGER,
  man_stops INTEGER,
  man_tackles INTEGER,
  man_targets INTEGER,
  man_touchdowns INTEGER,
  man_yards INTEGER,
  man_yards_after_catch INTEGER,
  man_yards_per_coverage_snap REAL,
  man_yards_per_reception REAL,
  penalties INTEGER,
  zone_assists INTEGER,
  zone_avg_depth_of_target REAL,
  zone_catch_rate REAL,
  zone_coverage_percent REAL,
  zone_coverage_snaps_per_reception REAL,
  zone_coverage_snaps_per_target REAL,
  zone_dropped_ints INTEGER,
  zone_forced_incompletes INTEGER,
  zone_forced_incompletion_rate REAL,
  zone_grades_coverage_defense REAL,
  zone_interceptions INTEGER,
  zone_longest INTEGER,
  zone_missed_tackle_rate REAL,
  zone_missed_tackles INTEGER,
  zone_pass_break_ups INTEGER,
  zone_qb_rating_against REAL,
  zone_receptions INTEGER,
  zone_snap_counts_coverage INTEGER,
  zone_snap_counts_coverage_percent REAL,
  zone_snap_counts_pass_play INTEGER,
  zone_stops INTEGER,
  zone_tackles INTEGER,
  zone_targets INTEGER,
  zone_touchdowns INTEGER,
  zone_yards INTEGER,
  zone_yards_after_catch INTEGER,
  zone_yards_per_coverage_snap REAL,
  zone_yards_per_reception REAL,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (season, season_type, week, player_id)
);
CREATE INDEX ix_core_pff_coverage_scheme_week_player ON core_pff_coverage_scheme_week(player_id);

-- offense/summary with week=<REG weeks>,28,29,30,32: PFF's server-AGGREGATED REG+POST line,
-- grades recomputed over the window (grades are not additive, so they are never summed).
-- One row per player per season, across teams (team = his last). Scope = season.
CREATE TABLE core_pff_offense_season (
  season INTEGER NOT NULL,
  weeks_requested TEXT NOT NULL,
  player_id INTEGER NOT NULL,
  player TEXT,
  position TEXT,
  team_name TEXT,
  team TEXT,
  franchise_id INTEGER,
  jersey_number TEXT,
  player_game_count INTEGER,
  draft_season INTEGER,
  eligible_season INTEGER,
  declined_penalties INTEGER,
  grades_hands_fumble REAL,
  grades_offense REAL,
  grades_offense_penalty REAL,
  grades_pass REAL,
  grades_pass_block REAL,
  grades_pass_route REAL,
  grades_run REAL,
  grades_run_block REAL,
  penalties INTEGER,
  snap_counts_pass INTEGER,
  snap_counts_pass_block INTEGER,
  snap_counts_pass_route INTEGER,
  snap_counts_run INTEGER,
  snap_counts_run_block INTEGER,
  snap_counts_total INTEGER,
  snap_counts_total_pass INTEGER,
  snap_counts_total_run INTEGER,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (season, player_id)
);

-- defense/summary with week=<REG weeks>,28,29,30,32: PFF's server-AGGREGATED REG+POST line,
-- grades recomputed over the window (grades are not additive, so they are never summed).
-- One row per player per season, across teams (team = his last). Scope = season.
CREATE TABLE core_pff_defense_season (
  season INTEGER NOT NULL,
  weeks_requested TEXT NOT NULL,
  player_id INTEGER NOT NULL,
  player TEXT,
  position TEXT,
  team_name TEXT,
  team TEXT,
  franchise_id INTEGER,
  jersey_number TEXT,
  player_game_count INTEGER,
  draft_season INTEGER,
  eligible_season INTEGER,
  assists INTEGER,
  batted_passes INTEGER,
  catch_rate REAL,
  declined_penalties INTEGER,
  forced_fumbles INTEGER,
  fumble_recoveries INTEGER,
  fumble_recovery_touchdowns INTEGER,
  grades_coverage_defense REAL,
  grades_defense REAL,
  grades_defense_penalty REAL,
  grades_pass_rush_defense REAL,
  grades_run_defense REAL,
  grades_tackle REAL,
  hits INTEGER,
  hurries INTEGER,
  interception_touchdowns INTEGER,
  interceptions INTEGER,
  longest INTEGER,
  missed_tackle_rate REAL,
  missed_tackles INTEGER,
  pass_break_ups INTEGER,
  penalties INTEGER,
  qb_rating_against REAL,
  receptions INTEGER,
  sacks INTEGER,
  safeties INTEGER,
  snap_counts_box INTEGER,
  snap_counts_corner INTEGER,
  snap_counts_coverage INTEGER,
  snap_counts_defense INTEGER,
  snap_counts_dl INTEGER,
  snap_counts_dl_a_gap INTEGER,
  snap_counts_dl_b_gap INTEGER,
  snap_counts_dl_outside_t INTEGER,
  snap_counts_dl_over_t INTEGER,
  snap_counts_fs INTEGER,
  snap_counts_offball INTEGER,
  snap_counts_pass_rush INTEGER,
  snap_counts_run_defense INTEGER,
  snap_counts_slot INTEGER,
  stops INTEGER,
  tackles INTEGER,
  tackles_for_loss INTEGER,
  targets INTEGER,
  total_pressures INTEGER,
  touchdowns INTEGER,
  yards INTEGER,
  yards_after_catch INTEGER,
  yards_per_reception REAL,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (season, player_id)
);
