-- FTN Data (REBUILD_DESIGN §4, Phase 5). Owner per table: registry/sources.toml. FTN wire
-- names verbatim; types from live 2021 + 2025 (+ 2026) responses. Framework columns: season,
-- season_type, week (the SCHEDULE's week, via the FTN game's own week field; FTN numbers POST
-- 19-22 like the schedule) and, for all-22, gid (the request's game).
-- FTN ids ARE gsis_ids (qb, skp*, def*, psr, trg, off*Id ...), so no crosswalk is needed.
-- core_participation (nflverse, 2016-2025) keeps its own table; the seam is a MART
-- (mart_participation_personnel), which is where the two sources meet, each row naming its source.

-- /games/{season}: FTN's schedule; the gid -> season/week map every other FTN table uses.
CREATE TABLE core_ftn_games (
  season INTEGER NOT NULL,
  gid INTEGER NOT NULL,
  seas INTEGER,
  week INTEGER,
  day TEXT,
  date TEXT,
  start_time TEXT,
  v TEXT,
  h TEXT,
  stad TEXT,
  temp INTEGER,
  hum INTEGER,
  wspd INTEGER,
  wdir TEXT,
  cond TEXT,
  surf TEXT,
  ou REAL,
  sprv REAL,
  ptsv INTEGER,
  ptsh INTEGER,
  updated TEXT,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (season, gid)
);

-- /games/{season}/plays (paginated; /plays caps a page at 1000). One row per play; off/def = teams.
CREATE TABLE core_ftn_plays (
  season INTEGER NOT NULL,
  season_type TEXT NOT NULL CHECK (season_type IN ('REG', 'POST')),
  week INTEGER NOT NULL,
  gid INTEGER,
  pid INTEGER NOT NULL,
  detail TEXT,
  off TEXT,
  def TEXT,
  type TEXT,
  len INTEGER,
  qtr INTEGER,
  min INTEGER,
  sec INTEGER,
  ptso INTEGER,
  ptsd INTEGER,
  timo INTEGER,
  timd INTEGER,
  dwn INTEGER,
  ytg INTEGER,
  yfog INTEGER,
  zone INTEGER,
  yds INTEGER,
  succ INTEGER,
  fd INTEGER,
  sg INTEGER,
  nh INTEGER,
  pts INTEGER,
  bc TEXT,
  kne INTEGER,
  dir TEXT,
  rtck1 TEXT,
  rtck2 TEXT,
  psr TEXT,
  comp INTEGER,
  spk INTEGER,
  loc TEXT,
  trg TEXT,
  dfb TEXT,
  dot INTEGER,
  ptck1 TEXT,
  ptck2 TEXT,
  sk1 TEXT,
  sk2 TEXT,
  ptm TEXT,
  pen TEXT,
  desc TEXT,
  pey INTEGER,
  act TEXT,
  ints TEXT,
  iry INTEGER,
  fum TEXT,
  frcv TEXT,
  fry INTEGER,
  forc TEXT,
  fuml INTEGER,
  saf TEXT,
  blk TEXT,
  brcv TEXT,
  fgxp TEXT,
  fkicker TEXT,
  dist INTEGER,
  good INTEGER,
  punter TEXT,
  pgro INTEGER,
  pnet INTEGER,
  ptb INTEGER,
  pr TEXT,
  pry INTEGER,
  pfc INTEGER,
  kicker TEXT,
  kgro INTEGER,
  knet INTEGER,
  ktb INTEGER,
  kr TEXT,
  kry INTEGER,
  td INTEGER,
  td_type TEXT,
  epa REAL,
  dpbk TEXT,
  stunt INTEGER,
  db_count INTEGER,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (pid)
);
CREATE INDEX ix_core_ftn_plays_week ON core_ftn_plays(season, season_type, week);

-- /games/{season}/participation: formation, QB + 5 skill players (pos, role), 5 defenders.
-- Position vocabulary CHANGED: 2021 'TE'; 2022+ 'Y-TE'/'H-TE' (handled in the mart, never renamed here).
CREATE TABLE core_ftn_participation (
  season INTEGER NOT NULL,
  season_type TEXT NOT NULL CHECK (season_type IN ('REG', 'POST')),
  week INTEGER NOT NULL,
  pid INTEGER NOT NULL,
  gid INTEGER,
  form TEXT,
  form_align TEXT,
  qb TEXT,
  qb_role TEXT,
  skp1 TEXT,
  skp1_pos TEXT,
  skp1_role TEXT,
  def1 TEXT,
  def1_pos TEXT,
  skp2 TEXT,
  skp2_pos TEXT,
  skp2_role TEXT,
  def2 TEXT,
  def2_pos TEXT,
  skp3 TEXT,
  skp3_pos TEXT,
  skp3_role TEXT,
  def3 TEXT,
  def3_pos TEXT,
  skp4 TEXT,
  skp4_pos TEXT,
  skp4_role TEXT,
  def4 TEXT,
  def4_pos TEXT,
  skp5 TEXT,
  skp5_pos TEXT,
  skp5_role TEXT,
  def5 TEXT,
  def5_pos TEXT,
  mot1 TEXT,
  mot2 TEXT,
  mot3 TEXT,
  mot4 TEXT,
  mot5 TEXT,
  cushion1 INTEGER,
  cushion2 INTEGER,
  cushion3 INTEGER,
  cushion4 INTEGER,
  cushion5 INTEGER,
  route1 TEXT,
  route2 TEXT,
  route3 TEXT,
  route4 TEXT,
  route5 TEXT,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (pid)
);
CREATE INDEX ix_core_ftn_participation_week ON core_ftn_participation(season, season_type, week);

-- /all22/game/{gid}: all 22 players per play (off1Id..off11Pos, def1Id..def11Pos). 2026+ only:
-- nflverse participation carries the same thing through 2025.
CREATE TABLE core_ftn_all22 (
  season INTEGER NOT NULL,
  season_type TEXT NOT NULL CHECK (season_type IN ('REG', 'POST')),
  week INTEGER NOT NULL,
  gid INTEGER NOT NULL,
  playId INTEGER NOT NULL,
  off1Id TEXT,
  off1Pos TEXT,
  off2Id TEXT,
  off2Pos TEXT,
  off3Id TEXT,
  off3Pos TEXT,
  off4Id TEXT,
  off4Pos TEXT,
  off5Id TEXT,
  off5Pos TEXT,
  off6Id TEXT,
  off6Pos TEXT,
  off7Id TEXT,
  off7Pos TEXT,
  off8Id TEXT,
  off8Pos TEXT,
  off9Id TEXT,
  off9Pos TEXT,
  off10Id TEXT,
  off10Pos TEXT,
  off11Id TEXT,
  off11Pos TEXT,
  def1Id TEXT,
  def1Pos TEXT,
  def2Id TEXT,
  def2Pos TEXT,
  def3Id TEXT,
  def3Pos TEXT,
  def4Id TEXT,
  def4Pos TEXT,
  def5Id TEXT,
  def5Pos TEXT,
  def6Id TEXT,
  def6Pos TEXT,
  def7Id TEXT,
  def7Pos TEXT,
  def8Id TEXT,
  def8Pos TEXT,
  def9Id TEXT,
  def9Pos TEXT,
  def10Id TEXT,
  def10Pos TEXT,
  def11Id TEXT,
  def11Pos TEXT,
  gameId INTEGER,
  load_id INTEGER NOT NULL REFERENCES load_log(load_id),
  PRIMARY KEY (playId)
);
CREATE INDEX ix_core_ftn_all22_week ON core_ftn_all22(season, season_type, week);
